name: 'music_stream'
version: '1.0.0'
config-version: 2

profile: 'music_stream'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  music_stream:
  staging:
    +materialized: view
  core:
    +materialized: table